"""Tests for src/knobe/assemble.py (WO-2 Part A).

Golden-file byte-identity is the headline requirement: vignettes.csv for
the real 105-family matrix must be byte-for-byte identical to what the
LEGACY repotentialexperiments/assemble_vignettes.py produces (line endings
included). tests/golden/vignettes_105.csv was generated by actually
running that legacy script against
data/authoring/ALL_DOMAINS_master_matrix.csv and copying its output --
see task-1-report.md for the exact command.
"""
import csv
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest
from pydantic import ValidationError

from knobe import assemble, cli
from knobe.schemas import (
    CuratedRow,
    FamilyRow,
    LabeledCount,
    ReleaseManifest,
    VignetteRow,
    write_csv_validated,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
MASTER_MATRIX = REPO_ROOT / "data" / "authoring" / "ALL_DOMAINS_master_matrix.csv"
GOLDEN_CSV = Path(__file__).resolve().parent / "golden" / "vignettes_105.csv"


# ---------------------------------------------------------------------------
# Golden-file byte-identity
# ---------------------------------------------------------------------------


class TestGoldenFile:
    def test_golden_file_committed_and_nonempty(self):
        assert GOLDEN_CSV.exists()
        assert GOLDEN_CSV.stat().st_size > 0

    def test_assemble_matches_legacy_golden_bytes(self, tmp_path):
        families = assemble.load_families(MASTER_MATRIX)
        rows = assemble.assemble(families)
        validated_rows = [VignetteRow(**row) for row in rows]

        out_csv = tmp_path / "vignettes_105.csv"
        assemble.write_csv(validated_rows, out_csv)

        produced = out_csv.read_bytes()
        expected = GOLDEN_CSV.read_bytes()
        assert produced == expected

    def test_golden_has_crlf_line_endings(self):
        """Pin the exact byte-level detail that would be lost by a
        text-mode / parsed-row comparison: csv.DictWriter's default
        dialect uses \\r\\n line terminators."""
        data = GOLDEN_CSV.read_bytes()
        assert b"\r\n" in data
        assert data.count(b"\r\n") == data.count(b"\n")  # every \n is part of \r\n

    def test_assembled_rows_count_and_shape(self):
        families = assemble.load_families(MASTER_MATRIX)
        assert len(families) == 105
        rows = assemble.assemble(families)
        assert len(rows) == 420  # 105 families x 4 variants (incl. NEU, spec §3.2)

    def test_assembled_output_passes_vignette_row_schema(self):
        """Requirement 5: after assembling, rows are validated as
        VignetteRows before write; the 105-matrix path must pass."""
        families = assemble.load_families(MASTER_MATRIX)
        rows = assemble.assemble(families)
        validated = [VignetteRow(**row) for row in rows]
        assert len(validated) == 420

    def test_real_matrix_has_no_validation_errors(self):
        families = assemble.load_families(MASTER_MATRIX)
        all_errors = []
        for i, fam in enumerate(families, start=2):
            errs, _warns = assemble.validate_family(fam, i)
            all_errors.extend(errs)
        assert all_errors == []


# ---------------------------------------------------------------------------
# Rejection tests -- one documented failure mode each (acceptance criteria)
# ---------------------------------------------------------------------------


def _valid_family(**overrides) -> dict:
    fam = dict(
        family_id="TST-MB-01",
        domain="Testing",
        valence="MB",
        nonmoral_subdomain="",
        agent="The tester",
        goal="pass the test suite",
        common_action="ran the standard test",
        uncommon_action="ran an unusual bespoke test",
        affected_entity="the other developers",
        low_evocative_outcome="a report showed the build had failed",
        high_evocative_outcome="teammates spent the weekend firefighting the outage",
        outcome_verb="break the shared build",
    )
    fam.update(overrides)
    return fam


class TestValidateFamilyRejections:
    def test_valid_family_has_no_errors(self):
        errors, _warnings = assemble.validate_family(_valid_family(), 2)
        assert errors == []

    def test_banned_word_in_outcome_verb_rejected(self):
        fam = _valid_family(outcome_verb="intentionally break the shared build")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("banned evaluative/mental-state language" in e for e in errors)

    def test_banned_word_in_low_evocative_outcome_rejected(self):
        fam = _valid_family(low_evocative_outcome="a report showed the manager was negligent")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("banned evaluative/mental-state language" in e for e in errors)

    def test_to_prefixed_goal_rejected(self):
        fam = _valid_family(goal="to pass the test suite")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("'goal' starts with \"to\"" in e for e in errors)

    def test_to_prefixed_action_rejected(self):
        fam = _valid_family(common_action="to run the standard test")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("'common_action' starts with \"to\"" in e for e in errors)

    def test_noun_phrase_outcome_verb_rejected(self):
        fam = _valid_family(outcome_verb="the breaking of the shared build")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("looks like a noun phrase" in e for e in errors)

    def test_nmb_missing_subdomain_rejected(self):
        fam = _valid_family(valence="NMB", nonmoral_subdomain="")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("requires a nonmoral_subdomain" in e for e in errors)

    def test_identical_common_uncommon_actions_rejected(self):
        fam = _valid_family(uncommon_action="ran the standard test")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("common_action and uncommon_action are identical" in e for e in errors)

    def test_identical_low_high_outcomes_rejected(self):
        fam = _valid_family(high_evocative_outcome="a report showed the build had failed")
        errors, _ = assemble.validate_family(fam, 2)
        assert any(
            "low_evocative_outcome and high_evocative_outcome are identical" in e for e in errors
        )

    def test_agent_not_capitalized_or_the_rejected(self):
        fam = _valid_family(agent="the tester")
        errors, _ = assemble.validate_family(fam, 2)
        assert any("should start with \"The \"" in e for e in errors)

    def test_low_high_low_overlap_is_warning_not_error(self):
        fam = _valid_family(
            low_evocative_outcome="quarterly figures dipped",
            high_evocative_outcome="a scandal erupted overnight",
        )
        errors, warnings = assemble.validate_family(fam, 2)
        assert errors == []
        assert any("share few content words" in w for w in warnings)


# ---------------------------------------------------------------------------
# Build/write helpers on a tiny synthetic matrix
# ---------------------------------------------------------------------------

_FAMILY_ASSEMBLY_FIELDNAMES = [
    "family_id", "domain", "valence", "nonmoral_subdomain", "agent", "goal",
    "common_action", "uncommon_action", "affected_entity",
    "low_evocative_outcome", "high_evocative_outcome", "outcome_verb",
]


def _write_family_csv(path: Path, families: list[dict], extra_fieldnames: list[str] | None = None) -> None:
    fieldnames = _FAMILY_ASSEMBLY_FIELDNAMES + (extra_fieldnames or [])
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(families)


def _two_family_matrix() -> list[dict]:
    return [
        _valid_family(family_id="TST-MB-01", valence="MB"),
        _valid_family(
            family_id="TST-MG-01", valence="MG",
            low_evocative_outcome="a report showed the build had passed",
            high_evocative_outcome="teammates were able to ship the release on schedule",
            outcome_verb="stabilize the shared build",
        ),
    ]


class TestAssembleAndWrite:
    def test_build_variant_uses_templates_from_constants(self):
        from knobe import constants

        fam = _valid_family()
        row = assemble.build_variant(fam, "common", "low")
        assert row["scenario"] == constants.SCENARIO_TEMPLATE.format(
            agent=fam["agent"], action=fam["common_action"], goal=fam["goal"],
            affected=fam["affected_entity"], outcome_verb=fam["outcome_verb"],
            outcome_text=fam["low_evocative_outcome"],
        )
        assert row["variant_id"] == "TST-MB-01-A"
        assert row["sign"] == "bad"

    def test_write_csv_round_trips_through_schema(self, tmp_path):
        rows = assemble.assemble(_two_family_matrix())
        validated = [VignetteRow(**r) for r in rows]
        out = tmp_path / "out.csv"
        assemble.write_csv(validated, out)
        with open(out, newline="", encoding="utf-8") as f:
            reloaded = [VignetteRow(**r) for r in csv.DictReader(f)]
        assert reloaded == validated

    def test_write_xlsx_writes_file_when_openpyxl_available(self, tmp_path):
        import openpyxl  # noqa: F401 -- skip test cleanly if genuinely unavailable

        families = _two_family_matrix()
        rows = assemble.assemble(families)
        out = tmp_path / "out.xlsx"
        wrote = assemble.write_xlsx(families, rows, out)
        assert wrote is True
        assert out.exists()

    def test_render_preview_writes_one_variant_per_family(self, tmp_path):
        families = _two_family_matrix()
        rows = assemble.assemble(families)
        out = tmp_path / "preview.txt"
        assemble.render_preview(families, rows, out)
        text = out.read_text(encoding="utf-8")
        assert "TST-MB-01" in text
        assert "TST-MG-01" in text
        assert text.count("=== ") == 2


# ---------------------------------------------------------------------------
# run() orchestration: error blocking, --force, output files
# ---------------------------------------------------------------------------


class TestRunOrchestration:
    def test_run_blocks_output_on_validation_errors_without_force(self, tmp_path, capsys):
        families = [_valid_family(uncommon_action="ran the standard test")]  # identical actions -> error
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families)
        out_prefix = tmp_path / "out"

        rc = assemble.run(input_csv, out_prefix)

        assert rc == 1
        assert not Path(f"{out_prefix}.csv").exists()

    def test_run_writes_output_with_force_despite_errors(self, tmp_path):
        families = [_valid_family(uncommon_action="ran the standard test")]
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families)
        out_prefix = tmp_path / "out"

        rc = assemble.run(input_csv, out_prefix, force=True)

        assert rc == 0
        assert Path(f"{out_prefix}.csv").exists()

    def test_run_succeeds_and_writes_all_three_outputs(self, tmp_path):
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, _two_family_matrix())
        out_prefix = tmp_path / "out"

        rc = assemble.run(input_csv, out_prefix)

        assert rc == 0
        assert Path(f"{out_prefix}.csv").exists()
        assert Path(f"{out_prefix}_preview.txt").exists()
        # .xlsx is best-effort (openpyxl optional); don't hard-require it here.


# ---------------------------------------------------------------------------
# Release mode
# ---------------------------------------------------------------------------


class TestReleaseMode:
    def _approved_families(self) -> list[dict]:
        fams = _two_family_matrix()
        for fam in fams:
            fam["human_approved"] = "True"
        return fams

    def _write_curated(self, path: Path, rows: list[dict], accept_all: bool = True, drop_variant: str | None = None) -> None:
        curated = []
        for row in rows:
            if drop_variant and row["variant_id"] == drop_variant:
                continue
            curated.append(
                CuratedRow(
                    **row,
                    reviewer_model="claude-test",
                    curation_date="2026-07-27",
                    accepted=accept_all,
                )
            )
        write_csv_validated(curated, path, CuratedRow)

    def test_release_success_writes_csv_and_verifiable_manifest(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])

        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]

        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)

        release_root = tmp_path / "release"
        release_dir = assemble.build_release(
            release="v9.9",
            input_path=input_csv,
            curated_path=curated_csv,
            validated_rows=validated_rows,
            n_families=len(loaded_families),
            changelog="test release",
            gates_passed=["G0"],
            release_root=release_root,
            git_commit="deadbeefcafe",
        )

        assert release_dir == release_root / "v9.9"
        csv_path = release_dir / "vignettes.csv"
        manifest_path = release_dir / "manifest.json"
        assert csv_path.exists()
        assert manifest_path.exists()

        manifest = ReleaseManifest.model_validate_json(manifest_path.read_text(encoding="utf-8"))
        assert manifest.release == "v9.9"
        assert manifest.git_commit == "deadbeefcafe"
        assert manifest.changelog == "test release"
        assert manifest.gates_passed == ["G0"]
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", manifest.created)

        # sha256 verifies against the actual bytes on disk.
        recomputed = hashlib.sha256(csv_path.read_bytes()).hexdigest()
        assert manifest.files["vignettes.csv"].sha256 == recomputed
        assert manifest.files["vignettes.csv"].rows == 8

        assert manifest.counts.families == 2
        assert manifest.counts.variants == 8
        # by_valence/by_domain report BOTH levels, labeled (researcher
        # decision d2, docs/DECISIONS_FOR_HUMANS.md item (d)): one family
        # each (MB, MG) -> 4 variants each.
        assert manifest.counts.by_valence == {
            "MB": LabeledCount(families=1, variants=4),
            "MG": LabeledCount(families=1, variants=4),
        }
        assert manifest.counts.by_domain == {"Testing": LabeledCount(families=2, variants=8)}

    def test_release_uses_real_git_commit_when_not_overridden(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)

        release_dir = assemble.build_release(
            release="v9.8",
            input_path=input_csv,
            curated_path=curated_csv,
            validated_rows=validated_rows,
            n_families=len(loaded_families),
            release_root=tmp_path / "release",
        )
        manifest = ReleaseManifest.model_validate_json((release_dir / "manifest.json").read_text())

        expected = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
        assert manifest.git_commit == expected

    def test_release_refused_when_family_missing_human_approved_column(self, tmp_path):
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, _two_family_matrix())  # no human_approved column at all
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError, match="human_approved"):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_release_refused_when_one_family_unapproved(self, tmp_path):
        families_dicts = self._approved_families()
        families_dicts[1]["human_approved"] = "False"
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError, match="TST-MG-01"):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_release_refused_when_curated_not_supplied(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError, match="--curated"):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=None,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_release_refused_when_variant_missing_acceptance(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows, drop_variant="TST-MB-01-A")
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError, match="TST-MB-01-A"):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_release_refused_when_variant_not_accepted(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows, accept_all=False)
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_release_refuses_to_overwrite_existing_release_dir(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)
        release_root = tmp_path / "release"
        existing = release_root / "v9.9"
        existing.mkdir(parents=True)
        (existing / "sentinel.txt").write_text("do not touch")

        with pytest.raises(assemble.ReleaseError, match="already exists"):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        # nothing added or removed from the pre-existing directory
        assert [p.name for p in existing.iterdir()] == ["sentinel.txt"]

    def test_release_extra_unknown_column_refuses_cleanly_not_with_raw_valueerror(self, tmp_path):
        """Regression for the reviewer finding: a matrix carrying an
        authoring-only column beyond the 12 canonical ones (e.g.
        "authoring_notes") used to blow straight through
        schemas.FamilyRow's extra="forbid" with a raw ValidationError
        instead of a clean ReleaseError refusal. Here the family is ALSO
        unapproved, so a refusal is still expected -- but it must come
        back as ReleaseError, not a raw pydantic ValidationError, and
        nothing must be written."""
        families_dicts = _two_family_matrix()  # no human_approved -> unapproved
        for fam in families_dicts:
            fam["authoring_notes"] = "internal reviewer scratch notes, not a schema field"
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["authoring_notes"])
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError, match="human_approved"):
            assemble.build_release(
                release="v9.9", input_path=input_csv, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_release_extra_unknown_column_tolerated_when_otherwise_approved(self, tmp_path):
        """Complement to the above: an extra authoring-only column must not
        by itself block an otherwise fully-approved, fully-curated release
        -- proving the fix tolerates the column rather than merely
        changing the exception type it crashes with."""
        families_dicts = self._approved_families()
        for fam in families_dicts:
            fam["authoring_notes"] = "internal reviewer scratch notes, not a schema field"
        input_csv = tmp_path / "input.csv"
        _write_family_csv(
            input_csv, families_dicts, extra_fieldnames=["human_approved", "authoring_notes"],
        )
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)
        release_root = tmp_path / "release"

        release_dir = assemble.build_release(
            release="v9.9", input_path=input_csv, curated_path=curated_csv,
            validated_rows=validated_rows, n_families=len(loaded_families),
            release_root=release_root, git_commit="deadbeef",
        )
        assert (release_dir / "vignettes.csv").exists()
        assert (release_dir / "manifest.json").exists()

    def test_release_refused_cleanly_on_xlsx_input(self, tmp_path):
        """Regression for the reviewer finding's second half: --release
        against an .xlsx input must fail with a clean ReleaseError, not an
        unhandled crash from trying to parse binary xlsx bytes as CSV
        text."""
        openpyxl = pytest.importorskip("openpyxl")

        families_dicts = self._approved_families()
        input_xlsx = tmp_path / "input.xlsx"
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "master_matrix"
        fieldnames = _FAMILY_ASSEMBLY_FIELDNAMES + ["human_approved"]
        ws.append(fieldnames)
        for fam in families_dicts:
            ws.append([fam.get(f, "") for f in fieldnames])
        wb.save(input_xlsx)

        loaded_families = assemble.load_families(input_xlsx)
        rows = assemble.assemble(loaded_families)
        validated_rows = [VignetteRow(**r) for r in rows]
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)
        release_root = tmp_path / "release"

        with pytest.raises(assemble.ReleaseError, match="CSV"):
            assemble.build_release(
                release="v9.9", input_path=input_xlsx, curated_path=curated_csv,
                validated_rows=validated_rows, n_families=len(loaded_families),
                release_root=release_root, git_commit="deadbeef",
            )
        assert not (release_root / "v9.9").exists()

    def test_run_end_to_end_with_release_flag(self, tmp_path):
        families_dicts = self._approved_families()
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, families_dicts, extra_fieldnames=["human_approved"])

        # Need curated.csv keyed to the *actual* assembled variant_ids/scenarios.
        loaded_families = assemble.load_families(input_csv)
        rows = assemble.assemble(loaded_families)
        curated_csv = tmp_path / "curated.csv"
        self._write_curated(curated_csv, rows)

        out_prefix = tmp_path / "out"
        release_root = tmp_path / "release"
        rc = assemble.run(
            input_csv, out_prefix,
            release="v9.9", curated=curated_csv, changelog="e2e test",
            gates_passed=["G0", "G1"], release_root=release_root,
        )
        assert rc == 0
        assert (release_root / "v9.9" / "vignettes.csv").exists()
        assert (release_root / "v9.9" / "manifest.json").exists()

    def test_real_repo_data_release_dir_untouched(self):
        """Safety net: nothing in this test module should ever write into
        the real data/release/ directory (append-only; brief explicitly
        says it must stay empty in git except README)."""
        real_release_dir = REPO_ROOT / "data" / "release"
        entries = sorted(p.name for p in real_release_dir.iterdir())
        assert entries == [".gitkeep", "README.md"]


# ---------------------------------------------------------------------------
# CLI wiring
# ---------------------------------------------------------------------------


class TestCLI:
    def test_assemble_subcommand_registered(self):
        assert "assemble" in cli.SUBCOMMANDS

    def test_cli_main_runs_assemble_successfully(self, tmp_path):
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, [_valid_family()])
        out_prefix = tmp_path / "out"

        rc = cli.main(["assemble", str(input_csv), str(out_prefix)])

        assert rc == 0
        assert Path(f"{out_prefix}.csv").exists()

    def test_cli_subprocess_console_script(self, tmp_path):
        input_csv = tmp_path / "input.csv"
        _write_family_csv(input_csv, [_valid_family()])
        out_prefix = tmp_path / "out"

        result = subprocess.run(
            [sys.executable, "-m", "knobe.cli", "assemble", str(input_csv), str(out_prefix)],
            capture_output=True, text=True, timeout=30,
        )
        assert result.returncode == 0, result.stderr
        assert Path(f"{out_prefix}.csv").exists()

    def test_cli_help_mentions_assemble(self, capsys):
        with pytest.raises(SystemExit):
            cli.build_parser().parse_args(["--help"])
        out = capsys.readouterr().out
        assert "assemble" in out
