"""S2: the deterministic vignette assembler (master spec §3.2; WO-2 Part A).

Behavior-preserving port of ``repotentialexperiments/assemble_vignettes.py``.
Every constant it needs (banned-word lists, aliases, the scenario/question
templates, variant letters, output field order) lives in ``constants.py``
and is imported from there -- nothing here redefines a competing copy
(common-context.md constraint 2, master spec §7.2).

Architecture (unchanged from the legacy script):
    SPREADSHEET (authoring layer, human-edited)
        -> load_families + validate_family (this module, deterministic, no LLM calls)
        -> assemble/build_variant
        -> vignettes.csv / .xlsx / preview.txt (pipeline artifacts)

``vignettes.csv`` output is required to be byte-identical to the legacy
script's output for the same input (spec §3.2, WO-2 acceptance criterion);
see ``tests/test_assemble.py``'s golden-file test, which compares raw bytes
against ``tests/golden/vignettes_105.csv`` (generated by actually running
the legacy script against the real 105-family matrix).

This module additionally adds ``--release`` mode (WO-2 Part A requirement
3): writes a frozen ``vignettes.csv`` + ``manifest.json`` into
``data/release/vX.Y/`` after verifying every family is human-approved and
every variant has an accepted curation row. Nothing is written if either
gate fails, and an existing release directory is never overwritten
(master spec §7.1's append-only rule).
"""
from __future__ import annotations

import csv
import hashlib
import re
import subprocess
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Sequence

from pydantic import ValidationError as PydanticValidationError

try:
    import openpyxl
except ImportError:  # pragma: no cover - exercised implicitly when openpyxl absent
    openpyxl = None

from knobe import constants
from knobe.schemas import (
    CuratedRow,
    FamilyRow,
    FileManifestEntry,
    LabeledCount,
    ReleaseCounts,
    ReleaseManifest,
    VignetteRow,
    read_csv_validated,
    write_csv_validated,
)


class ReleaseError(RuntimeError):
    """Raised when ``--release`` mode refuses to write (WO-2 Part A
    requirement 3). Every check this can raise from happens before any
    filesystem write, so raising it always means nothing was written."""


# ---------------------------------------------------------------------------
# Ingestion -- ported from assemble_vignettes.py's load_families/_normalize_header
# ---------------------------------------------------------------------------


def _normalize_header(raw_headers) -> dict[int, str]:
    """Map arbitrary spreadsheet headers onto the canonical field names via
    ``constants.ALIASES`` (case-insensitive). Returns {col_index: canonical_name}."""
    lookup: dict[str, str] = {}
    for canonical, variants in constants.ALIASES.items():
        for v in variants:
            lookup[v.lower().strip()] = canonical

    mapping: dict[int, str] = {}
    for i, h in enumerate(raw_headers):
        if h is None:
            continue
        key = str(h).lower().strip()
        if key in lookup:
            mapping[i] = lookup[key]
    return mapping


def load_families(path: str | Path, sheet_name: str = "master_matrix") -> list[dict]:
    """Load family rows from an .xlsx (preferring ``sheet_name``, falling
    back to the first sheet) or a .csv. Returns a list of dicts keyed by
    canonical field names (only the 12 assembly columns known via
    ``constants.ALIASES`` -- provenance columns like ``human_approved`` are
    read separately, by a light direct scan, by the release-mode checks
    below (see ``_check_family_approval``))."""
    path = Path(path)
    ext = path.suffix.lower()

    if ext in (".xlsx", ".xlsm"):
        if openpyxl is None:
            raise RuntimeError("openpyxl is required to read .xlsx input")
        wb = openpyxl.load_workbook(path, data_only=True)
        ws = wb[sheet_name] if sheet_name in wb.sheetnames else wb[wb.sheetnames[0]]
        rows = list(ws.iter_rows(values_only=True))
        headers, data_rows = rows[0], rows[1:]
    elif ext == ".csv":
        with open(path, newline="", encoding="utf-8") as f:
            reader = list(csv.reader(f))
        headers, data_rows = reader[0], reader[1:]
    else:
        raise ValueError(f"Unsupported input file type: {ext}")

    mapping = _normalize_header(headers)
    unmapped = [h for i, h in enumerate(headers) if i not in mapping and h]
    if unmapped:
        print(f"NOTE: columns not recognized and ignored: {unmapped}")

    families = []
    for row in data_rows:
        if row is None or all(c is None or str(c).strip() == "" for c in row):
            continue  # skip blank rows
        d = {}
        for i, val in enumerate(row):
            if i in mapping:
                d[mapping[i]] = "" if val is None else str(val).strip()
        families.append(d)
    return families


# ---------------------------------------------------------------------------
# Validation -- ported from assemble_vignettes.py's validate_family/check_grammatical_fit
# ---------------------------------------------------------------------------


def validate_family(fam: dict, row_num: int) -> tuple[list[str], list[str]]:
    """Returns (errors, warnings). Errors block output (real problems:
    missing data, banned language, identical text). Warnings are printed
    but do not block (soft heuristics that can false-positive on
    legitimately-phrased human-authored content, e.g. low word overlap
    when a matched pair simply uses different vocabulary)."""
    errors = []
    warnings = []

    for field in constants.REQUIRED_FIELDS:
        if not fam.get(field):
            errors.append(f"row {row_num} ({fam.get('family_id', '?')}): missing required field '{field}'")

    valence = fam.get("valence", "")
    if valence not in constants.VALID_VALENCES:
        errors.append(
            f"row {row_num} ({fam.get('family_id', '?')}): invalid valence '{valence}' "
            f"(must be one of {sorted(constants.VALID_VALENCES)})"
        )
        return errors, warnings  # can't validate further without a valid valence

    subdomain = fam.get("nonmoral_subdomain", "")
    if valence in constants.NONMORAL_VALENCES:
        if not subdomain:
            errors.append(f"row {row_num} ({fam['family_id']}): {valence} requires a nonmoral_subdomain")
        elif subdomain not in constants.VALID_SUBDOMAINS:
            errors.append(
                f"row {row_num} ({fam['family_id']}): nonmoral_subdomain '{subdomain}' "
                f"not in {sorted(constants.VALID_SUBDOMAINS)}"
            )
    # NOTE (bug fix from prior session): an EMPTY nonmoral_subdomain on a
    # MB/MG/NEU row is valid (means "not applicable") and must NOT be
    # flagged as missing -- only NMB/NMG rows require it.

    # Banned-language check on consequence fields only.
    for field in ("low_evocative_outcome", "high_evocative_outcome", "outcome_verb"):
        text = fam.get(field, "").lower()
        hits = sorted({w for w in constants.ALL_BANNED if re.search(rf"\b{w}\w*\b", text)})
        if hits:
            errors.append(
                f"row {row_num} ({fam['family_id']}): '{field}' contains banned "
                f"evaluative/mental-state language: {hits}"
            )

    # Low/high must differ (else evocativeness manipulation is inert).
    low = fam.get("low_evocative_outcome", "")
    high = fam.get("high_evocative_outcome", "")
    if low and high:
        if low.strip().lower() == high.strip().lower():
            errors.append(
                f"row {row_num} ({fam['family_id']}): low_evocative_outcome and "
                f"high_evocative_outcome are identical"
            )
        else:
            low_words = set(re.findall(r"[a-z]+", low.lower())) - constants.STOPWORDS
            high_words = set(re.findall(r"[a-z]+", high.lower())) - constants.STOPWORDS
            overlap = low_words & high_words
            if len(overlap) < 2:
                warnings.append(
                    f"row {row_num} ({fam['family_id']}): low/high share few content words "
                    f"({sorted(overlap)}) -- eyeball that both describe the same underlying "
                    f"event (this is often fine if they just use different vocabulary)"
                )

    # Common/uncommon actions must differ.
    if fam.get("common_action", "").strip().lower() == fam.get("uncommon_action", "").strip().lower():
        errors.append(f"row {row_num} ({fam['family_id']}): common_action and uncommon_action are identical")

    errors.extend(check_grammatical_fit(fam, row_num))

    return errors, warnings


# Fields that get slotted directly after a fixed template word, and would
# therefore double up or read wrong if the field itself repeats that word.
# This is a MECHANICAL check (does the string fit the fixed slot), not a
# content/style judgment -- added after a real bug where an elicitation
# script combined "cause" (a template word) with an outcome_verb field
# that was itself already a verb phrase, producing "intentionally cause
# contaminate the town's water supply." Catching the noun-phrase-vs-verb-
# phrase confusion here, at authoring time, is cheaper than catching it
# downstream in every script that later consumes these fields.
_LEADING_TO = re.compile(r"^\s*to\b", re.IGNORECASE)
_LEADING_ARTICLE = re.compile(r"^\s*(the|a|an)\b", re.IGNORECASE)


def check_grammatical_fit(fam: dict, row_num: int) -> list[str]:
    """Heuristic, not a grammar checker -- catches the specific class of
    slot-mismatch that has actually caused a bug in this project, not every
    possible grammatical error. Manual read-through (e.g. via
    render_preview() below) remains the real backstop for anything subtler
    than these mechanical signals."""
    errors = []
    fid = fam.get("family_id", "?")

    # goal and both actions slot in as "... to {goal}." / "{agent} {action}
    # to ..." -- a field starting with "to" would double the template's
    # own "to", e.g. "to to cut costs" or "{agent} to switch to...".
    for field in ("goal", "common_action", "uncommon_action"):
        val = fam.get(field, "")
        if val and _LEADING_TO.match(val):
            errors.append(
                f"row {row_num} ({fid}): '{field}' starts with \"to\" -- the template "
                f"already supplies \"to\", so this would double up (e.g. \"... to to {val}\"). "
                f"Rewrite '{field}' to start with the bare verb instead."
            )

    # outcome_verb slots in as "knew that this would {outcome_verb}: ..."
    # and reused verbatim in q_intentionality as "intentionally {outcome_verb}".
    # It must be a VERB phrase ("contaminate the water supply"), not a NOUN
    # phrase ("the contamination of the water supply") -- a leading
    # article is the clearest mechanical signal of the latter.
    outcome_verb = fam.get("outcome_verb", "")
    if outcome_verb and _LEADING_ARTICLE.match(outcome_verb):
        errors.append(
            f"row {row_num} ({fid}): 'outcome_verb' (\"{outcome_verb}\") looks like a noun "
            f"phrase (starts with the/a/an), but it needs to be a bare verb phrase -- it's "
            f"inserted directly after \"intentionally\" and after \"would\". "
            f"E.g. use \"contaminate the water supply\", not \"the contamination of the water supply\"."
        )

    # agent must start with "The " or be a capitalized proper name, since
    # _lower_agent()'s casing logic assumes one of those two shapes.
    agent = fam.get("agent", "")
    if agent and not (agent.startswith("The ") or agent[0].isupper()):
        errors.append(
            f"row {row_num} ({fid}): 'agent' (\"{agent}\") should start with \"The \" "
            f"(a role, e.g. \"The plant manager\") or be a capitalized proper name "
            f"(e.g. \"Maria\") -- lowercase-first-word agents will get mis-cased when "
            f"the template lowercases it for mid-sentence use."
        )

    return errors


# ---------------------------------------------------------------------------
# Assembly -- ported from assemble_vignettes.py's build_variant/assemble
# ---------------------------------------------------------------------------


def _lower_agent(agent: str) -> str:
    if agent.startswith("The "):
        return "the " + agent[4:]
    return agent[0].lower() + agent[1:] if agent else agent


def build_variant(fam: dict, typicality: str, evocativeness: str) -> dict:
    agent = fam["agent"]
    action = fam["common_action"] if typicality == "common" else fam["uncommon_action"]
    outcome_text = fam["low_evocative_outcome"] if evocativeness == "low" else fam["high_evocative_outcome"]
    outcome_verb = fam["outcome_verb"]
    goal = fam["goal"]
    affected = fam["affected_entity"]

    scenario = constants.SCENARIO_TEMPLATE.format(
        agent=agent, action=action, goal=goal, affected=affected,
        outcome_verb=outcome_verb, outcome_text=outcome_text,
    )

    agent_lower = _lower_agent(agent)
    q_intentionality = constants.Q_INTENTIONALITY_TEMPLATE.format(
        agent_lower=agent_lower, outcome_verb=outcome_verb,
    )

    letter = constants.VARIANT_LETTER[(typicality, evocativeness)]
    row = {
        "variant_id": f"{fam['family_id']}-{letter}",
        "family_id": fam["family_id"],
        "domain": fam["domain"],
        "valence": fam["valence"],
        "nonmoral_subdomain": fam.get("nonmoral_subdomain", ""),
        "sign": constants.SIGN_BY_VALENCE[fam["valence"]],
        "typicality": typicality,
        "evocativeness": evocativeness,
        "scenario": scenario,
        "q_intentionality": q_intentionality,
    }
    for qkey, template in constants.QUESTIONS.items():
        row[qkey] = template.format(agent_lower=agent_lower)
    return row


def assemble(families: list[dict]) -> list[dict]:
    rows = []
    for fam in families:
        for typicality in ("common", "uncommon"):
            for evocativeness in ("low", "high"):
                rows.append(build_variant(fam, typicality, evocativeness))
    return rows


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def write_csv(validated_rows: list[VignetteRow], path: str | Path) -> None:
    """Writes vignettes.csv. Delegates the actual write to
    ``schemas.write_csv_validated`` so exactly one place in the package owns
    the byte-for-byte CSV-writing behavior (csv.DictWriter defaults: line
    endings, quoting) that the golden-file test in tests/test_assemble.py
    checks against the legacy script's real output."""
    write_csv_validated(validated_rows, path, VignetteRow)


def write_xlsx(families: list[dict], rows: list[dict], path: str | Path) -> bool:
    """Writes the two-sheet workbook (master_matrix + vignettes). Returns
    False (writes nothing) if openpyxl isn't installed -- it's an optional
    dependency (pyproject.toml already lists it as a base dependency, but
    this module tolerates its absence like the legacy script did)."""
    if openpyxl is None:
        return False
    wb = openpyxl.Workbook()
    ws1 = wb.active
    ws1.title = "master_matrix"
    mm_fields = FamilyRow.csv_fieldnames()  # the 12 canonical master_matrix columns
    ws1.append(mm_fields)
    for fam in families:
        ws1.append([fam.get(f, "") for f in mm_fields])

    ws2 = wb.create_sheet("vignettes")
    ws2.append(constants.OUTPUT_FIELDNAMES)
    for r in rows:
        ws2.append([r.get(f, "") for f in constants.OUTPUT_FIELDNAMES])

    wb.save(str(path))
    return True


def render_preview(families: list[dict], rows: list[dict], path: str | Path) -> None:
    """Writes one fully-composed variant per family (the 'A' variant) to a
    plain-text file for manual read-through -- the backstop for anything
    the mechanical checks in check_grammatical_fit() can't catch (awkward
    phrasing, subtly wrong verb forms, tone). Automated checks catch
    whether a string FITS the slot; a human still has to judge whether it
    READS WELL once it does."""
    by_family: dict[str, list[dict]] = {}
    for r in rows:
        by_family.setdefault(r["family_id"], []).append(r)

    with open(path, "w", encoding="utf-8") as f:
        for fam in families:
            fid = fam.get("family_id", "?")
            variant_a = next((r for r in by_family.get(fid, []) if r["variant_id"].endswith("-A")), None)
            if not variant_a:
                continue
            f.write(f"=== {fid} ({fam.get('valence', '?')}) ===\n")
            f.write(variant_a["scenario"] + "\n")
            f.write(f"  Q1: {variant_a['q_intentionality']}\n")
            f.write(f"  Q2: {variant_a['q_blame']}\n\n")


# ---------------------------------------------------------------------------
# Release mode (WO-2 Part A requirement 3; master spec §3.10, §7.1)
# ---------------------------------------------------------------------------

def _repo_root() -> Path:
    """Repo root, derived from this source file's location (works for the
    editable install this package is always run from)."""
    return Path(__file__).resolve().parents[2]


def _default_release_root() -> Path:
    """``data/release/`` under the repo root -- NOT the caller's cwd, so
    ``knobe assemble --release ...`` writes to the right place regardless
    of the directory it's invoked from."""
    return _repo_root() / "data" / "release"


def _git_commit_hash(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=repo_root, capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise ReleaseError(
            f"could not determine git_commit via `git rev-parse HEAD` in {repo_root}: "
            f"{result.stderr.strip()}"
        )
    return result.stdout.strip()


def _truthy(v) -> bool:
    """Same coercion semantics as ``schemas._coerce_bool`` (true/1/yes,
    case-insensitive; everything else -- including missing -- is False),
    duplicated locally as a tiny helper rather than reaching into that
    module's private function. This is ordinary truthy-string parsing, not
    a frozen scientific instrument, so a small local copy is fine."""
    if isinstance(v, bool):
        return v
    if v is None:
        return False
    return str(v).strip().lower() in ("true", "1", "yes")


def _check_family_approval(input_path: Path) -> list[str]:
    """Returns the family_ids of every family row lacking
    ``human_approved == True``.

    Deliberately does NOT round-trip the raw file through
    ``schemas.FamilyRow`` (which has ``extra="forbid"``): a matrix that
    carries any authoring-only column beyond the 12 canonical ones (e.g.
    "authoring_notes") would then crash release mode with a raw
    ``ValidationError`` instead of refusing cleanly, or worse, would block
    an otherwise-fine release entirely. Instead this reuses
    ``_normalize_header`` -- the same ALIASES-based, tolerant header
    mapping ``load_families`` uses for assembly -- to locate the
    ``family_id`` column, plus a light direct scan for a literal
    ``human_approved`` header (not in ``constants.ALIASES``, since it's a
    WO-1 provenance column, not one of the legacy 12). A matrix without
    the column at all means every row defaults to unapproved, per the
    brief.

    Raises ``ReleaseError`` (never a raw exception) if ``input_path`` isn't
    a .csv, is empty, or has no recognizable family_id column -- release
    mode's provenance check only supports .csv input; assemble .xlsx
    normally, then re-run with ``--release`` against an exported .csv."""
    input_path = Path(input_path)
    if input_path.suffix.lower() != ".csv":
        raise ReleaseError(
            f"--release mode requires CSV input for the human_approved provenance check "
            f"(got {input_path.name!r}, a {input_path.suffix or '(no extension)'} file). "
            f"Assemble from .xlsx normally, then re-run --release against an exported .csv."
        )

    with open(input_path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    if not rows:
        raise ReleaseError(f"{input_path} is empty -- cannot check human_approved.")
    headers, data_rows = rows[0], rows[1:]

    mapping = _normalize_header(headers)
    family_id_idx = next((i for i, canonical in mapping.items() if canonical == "family_id"), None)
    if family_id_idx is None:
        raise ReleaseError(f"{input_path} has no recognizable family_id column.")
    approved_idx = next(
        (i for i, h in enumerate(headers) if h is not None and str(h).strip().lower() == "human_approved"),
        None,
    )

    unapproved = []
    for row in data_rows:
        if row is None or all(c is None or str(c).strip() == "" for c in row):
            continue  # skip blank rows, matching load_families
        family_id = row[family_id_idx].strip() if family_id_idx < len(row) else "?"
        approved = _truthy(row[approved_idx]) if approved_idx is not None and approved_idx < len(row) else False
        if not approved:
            unapproved.append(family_id)
    return unapproved


def _check_curation_acceptance(variant_ids: Sequence[str], curated_path: Path) -> list[str]:
    """Returns the variant_ids that lack an ``accepted == True`` row in
    curated_path."""
    curated_rows = read_csv_validated(curated_path, CuratedRow)
    accepted = {r.variant_id for r in curated_rows if r.accepted}
    return [v for v in variant_ids if v not in accepted]


def _labeled_counts(
    validated_rows: list[VignetteRow], *, key: Callable[[VignetteRow], str]
) -> dict[str, LabeledCount]:
    """Groups ``validated_rows`` by ``key(row)`` (valence or domain) and
    reports BOTH levels per group, per docs/DECISIONS_FOR_HUMANS.md item
    (d2) (researcher directive, 2026-07-28): variant count (every row in
    the group) and family count (the number of DISTINCT family_ids in the
    group -- valence/domain are family-level attributes inherited
    unchanged into every variant, so counting distinct family_ids here is
    exact and doesn't need the raw family list or any assumption about how
    many variants a family produces)."""
    variant_counts = Counter(key(r) for r in validated_rows)
    family_ids_by_group: dict[str, set[str]] = {}
    for r in validated_rows:
        family_ids_by_group.setdefault(key(r), set()).add(r.family_id)
    return {
        group: LabeledCount(families=len(family_ids_by_group[group]), variants=variant_counts[group])
        for group in variant_counts
    }


def build_release(
    *,
    release: str,
    input_path: Path,
    curated_path: Path | None,
    validated_rows: list[VignetteRow],
    n_families: int,
    changelog: str = "",
    gates_passed: Sequence[str] | None = None,
    release_root: Path | None = None,
    git_commit: str | None = None,
) -> Path:
    """Writes ``vignettes.csv`` + ``manifest.json`` into
    ``release_root/release/``, after verifying:
      - every family in ``input_path`` has ``human_approved == True``, and
      - ``curated_path`` is supplied and every variant_id in
        ``validated_rows`` has an ``accepted == True`` row in it.
    Raises ``ReleaseError`` (nothing written) if either gate fails, or if
    the release directory already exists (master spec §7.1's append-only
    rule -- releases are never overwritten)."""
    release_root = release_root if release_root is not None else _default_release_root()
    release_dir = Path(release_root) / release

    if release_dir.exists():
        raise ReleaseError(
            f"release directory {release_dir} already exists -- releases are append-only "
            f"(master spec §7.1); cut a new release instead of overwriting."
        )

    unapproved = _check_family_approval(Path(input_path))
    if unapproved:
        raise ReleaseError(
            f"refusing release {release!r}: {len(unapproved)} family row(s) lack "
            f"human_approved == True: {unapproved}"
        )

    if curated_path is None:
        raise ReleaseError(f"refusing release {release!r}: --curated is required for --release mode.")

    missing = _check_curation_acceptance([r.variant_id for r in validated_rows], Path(curated_path))
    if missing:
        raise ReleaseError(
            f"refusing release {release!r}: {len(missing)} variant(s) lack an accepted == True "
            f"row in {curated_path}: {missing}"
        )

    git_commit = git_commit if git_commit is not None else _git_commit_hash(_repo_root())

    release_dir.mkdir(parents=True)
    csv_path = release_dir / "vignettes.csv"
    write_csv(validated_rows, csv_path)

    sha256 = hashlib.sha256(csv_path.read_bytes()).hexdigest()
    by_valence = _labeled_counts(validated_rows, key=lambda r: r.valence)
    by_domain = _labeled_counts(validated_rows, key=lambda r: r.domain)

    manifest = ReleaseManifest(
        release=release,
        created=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        git_commit=git_commit,
        files={"vignettes.csv": FileManifestEntry(sha256=sha256, rows=len(validated_rows))},
        counts=ReleaseCounts(
            families=n_families, variants=len(validated_rows),
            by_valence=by_valence, by_domain=by_domain,
        ),
        gates_passed=list(gates_passed) if gates_passed else [],
        changelog=changelog,
    )
    (release_dir / "manifest.json").write_text(manifest.model_dump_json(indent=2) + "\n", encoding="utf-8")

    return release_dir


# ---------------------------------------------------------------------------
# CLI-facing orchestration (called by knobe.cli's "assemble" subcommand)
# ---------------------------------------------------------------------------


def run(
    input_path: str | Path,
    out_prefix: str | Path,
    *,
    force: bool = False,
    release: str | None = None,
    curated: str | Path | None = None,
    changelog: str = "",
    gates_passed: Sequence[str] | None = None,
    release_root: str | Path | None = None,
) -> int:
    """Full assemble pipeline: load -> validate -> assemble -> validate
    output against VignetteRow -> write csv/xlsx/preview -> optionally
    write a release. Returns a process-style exit code (0 success, 1
    failure) rather than raising, except ``ReleaseError`` from a refused
    ``--release`` is caught and reported the same way."""
    input_path = Path(input_path)

    families = load_families(input_path)
    print(f"Loaded {len(families)} family rows from {input_path}")

    all_errors: list[str] = []
    all_warnings: list[str] = []
    for i, fam in enumerate(families, start=2):  # +2: header is row 1
        errs, warns = validate_family(fam, i)
        all_errors.extend(errs)
        all_warnings.extend(warns)

    if all_warnings:
        print(f"\n{len(all_warnings)} WARNING(S) -- worth a human eyeball, but not blocking:")
        for w in all_warnings:
            print(" -", w)

    if all_errors:
        print(f"\n{len(all_errors)} VALIDATION ERROR(S) -- fix these in the spreadsheet before re-running:")
        for e in all_errors:
            print(" -", e)
        if not force:
            print("\nNo output written. (Pass --force to write anyway, if you want to inspect partial output.)")
            return 1
        print("\n--force passed: writing output despite the errors above.")

    rows = assemble(families)
    print(f"Assembled {len(rows)} vignette variants from {len(families)} families.")

    try:
        validated_rows = [VignetteRow(**row) for row in rows]
    except PydanticValidationError as exc:
        print(f"\nASSEMBLED OUTPUT FAILED SCHEMA VALIDATION (spec §7.3) -- no output written:\n{exc}")
        return 1

    csv_path = Path(f"{out_prefix}.csv")
    write_csv(validated_rows, csv_path)
    print(f"Wrote {csv_path}")

    xlsx_path = Path(f"{out_prefix}.xlsx")
    if write_xlsx(families, rows, xlsx_path):
        print(f"Wrote {xlsx_path}")
    else:
        print("openpyxl not installed -- skipped .xlsx output")

    preview_path = Path(f"{out_prefix}_preview.txt")
    render_preview(families, rows, preview_path)
    print(
        f"Wrote {preview_path} -- one example variant per family, for manual read-through "
        f"(automated checks only catch structural fit, not whether it reads well)"
    )

    if release:
        try:
            release_dir = build_release(
                release=release,
                input_path=input_path,
                curated_path=Path(curated) if curated else None,
                validated_rows=validated_rows,
                n_families=len(families),
                changelog=changelog,
                gates_passed=gates_passed,
                release_root=Path(release_root) if release_root else None,
            )
        except ReleaseError as exc:
            print(f"\nRELEASE REFUSED: {exc}")
            return 1
        print(f"Wrote release {release_dir}")

    return 0
